require("plugins.nvim-tree")
require("plugins.nvim-lspconfig")
require("plugins.nvim-lightbulb")
require("plugins.nvim-cmp")
require("plugins.nvim-lspconfig")
require("plugins.nvim-dap")
require("plugins.nvim-dap-ui")
require("plugins.nvim-tree")
require("plugins.nvim-tmux-navigation")
require("plugins.gitsigns")
require("plugins.lualine")
require("plugins.neoformat")
require("plugins.lspkind")
require("plugins.treesitter")

require("nvim-autopairs").setup()
require("trouble").setup()
require("lsp_signature").setup()
