require("plugins.lsp-configs.cpp")
require("plugins.lsp-configs.web")
require("plugins.lsp-configs.lua")
require("plugins.lsp-configs.python")
require("plugins.lsp-configs.cmake")
require("plugins.lsp-configs.bash")
require("plugins.lsp-configs.docker")
require("plugins.lsp-configs.yaml")
